blank_issues_enabled: false
contact_links:
  - name: Wiki
    url: https://wiki.starcitizen-lug.org
    about: Problems running or installing Star Citizen, troubleshooting steps, and recent news/changes.
  - name: Community Support
    url: https://discord.gg/QRexSTkF25
    about: Get help from the community in our Discord tech support channel.
