on:
  create:
    tags:
      - 'v[0-9].[0-9]'
      - 'v[0-9].[0-9][0-9]'

name: Release AppImage

permissions:
  contents: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      tag: ${{ github.ref_name }}
    permissions:
      contents: write

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v6
        with:
          name: LUG-Helper-${{ github.ref_name }}.AppImage

      - name: Create GitHub release
        uses: softprops/action-gh-release@v3
        with:
          name: lug helper ${{ github.ref_name }}
          files: LUG-Helper-${{ github.ref_name }}.AppImage
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
